
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: blog_tech_django
    environment:
      - DJANGO_SETTINGS_MODULE=blog_heho.settings.development
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=dev-secret-key-change-in-production-only
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - .:/app  # Mount the code folder for live editing
    command: bash -c "ls && ./wait-for-it.sh postgres:5432 && python blog_heho/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

    # Other overrides or specific dev settings
